---
- name: "Configure golder image"
  hosts: localhost
  become: true

  tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true

    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: "Deploy application source files to web root"
      ansible.builtin.copy:
        src: ../../app/
        dest: /var/www/html/
        mode: '0644'
        directory_mode: '0755'

    - name: "Ensure Nginx is started"
      ansible.builtin.service:
        name: nginx
        state: started
