name: "PR: Validate & Lint"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ansible/**'
      - 'packer/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PACKER_VERSION: "1.15.4"
  PROJECT_ID_PLACEHOLDER: "random"
  IMAGE_VERSION_PLACEHOLDER: "1.1.1"

jobs:
  validate_packer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packer/server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Formatting Packer
        run: packer fmt -check -recursive .

      - name: Init Packer
        run: packer init .

      - name: Validate Packer
        run: |
          packer validate \
          -var "project_id=${{ env.PROJECT_ID_PLACEHOLDER }}" \
          -var "image_version=${{ env.IMAGE_VERSION_PLACEHOLDER }}" \
          .

  validate_ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible/playbooks

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip && \
          pip install ansible ansible-lint

      - name: Lint Ansible
        run: ansible-lint .

      - name: Check Ansible playbook syntax
        run: ansible-playbook --syntax-check ./setup.yml


